version: '2'

services:
  nginx:
    build:
      context: nginx/
      args:
        KLARA_REV: $KLARA_REV
    ports:
        - 80:80
    command: /entrypoint.sh
    depends_on:
      - klara-web
    volumes:
        - ./klara-nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - KLARA_REV=$KLARA_REV
    networks:
      klaranet:
        aliases:
          - klara-nginx
  klara-web:
    build:
      context: klara-web/
      args:
        - KLARA_REV=$KLARA_REV
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - BASE_URL=$BASE_URL
        - WEB_ENC_KEY=$WEB_ENC_KEY
    command: /entrypoint.sh
    depends_on:
      - klara-dispatcher
    ports:
      - "9000:9000"
    environment:
      - KLARA_REV=$KLARA_REV
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    networks:
      klaranet:
        aliases:
          - klara-web
  klara-dispatcher:
    build:
      context: klara-dispatcher/
      args:
        KLARA_REV: $KLARA_REV
    mem_limit: 1G
    command: /entrypoint.sh
    depends_on:
      - klara-db
    environment:
      - KLARA_REV=$KLARA_REV
    networks:
      klaranet:
        aliases:
          - klara-dispatcher
  klara-worker:
    build:
      context: klara-worker/
      args:
        KLARA_REV: $KLARA_REV
    mem_limit: 1G
    command: /entrypoint.sh
    depends_on:
      - klara-dispatcher
    volumes:
      - ./klara-repository/repository:/var/projects/klara/repository
    environment:
      - KLARA_REV=$KLARA_REV
    networks:
      klaranet:
        aliases:
          - klara-worker
  klara-db:
    restart: always
    image: mariadb:10
    mem_limit: 1G
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./klara-db/datadir:/var/lib/mysql
    networks:
      klaranet:
        aliases:
          - klara-db

networks:
  klaranet:
    driver: bridge
