version: '2'

services:
  nginx:
    build:
      context: nginx/
      args:
        KLARA_REV: $KLARA_REV
    ports:
        - 80:80
    command: /entrypoint.sh
    depends_on:
      - klara-web
    volumes:
        # - "G:/nginx/site.conf:/etc/nginx/conf.d/default.conf"
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - KLARA_REV=$KLARA_REV
    container_name: nginx
    networks:
      klaranet:
        aliases:
          - nginx
  klara-web:
    build:
      context: klara-web/
      args:
        - KLARA_REV=$KLARA_REV
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - BASE_URL=$BASE_URL
        - WEB_ENC_KEY=$WEB_ENC_KEY
    command: /entrypoint.sh
    depends_on:
      - klara-dispatcher
      - klara-db
    ports:
      - "9000:9000"
    environment:
      - KLARA_REV=$KLARA_REV
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    container_name: klara-web
    networks:
      klaranet:
        aliases:
          - klara-web
  klara-dispatcher:
    build:
      context: klara-dispatcher/
      args:
        KLARA_REV: $KLARA_REV
    mem_limit: 1G
    command: /entrypoint.sh
    depends_on:
      - klara-db
    environment:
      - KLARA_REV=$KLARA_REV
    container_name: klara-dispatcher
    networks:
      klaranet:
        aliases:
          - klara-dispatcher
  klara-worker:
    build:
      context: klara-worker/
      args:
        KLARA_REV: $KLARA_REV
    mem_limit: 1G
    command: /entrypoint.sh
    depends_on:
      - klara-dispatcher
    volumes:
      - "G:/klara-repository/repository:/var/projects/klara/repository"
    environment:
      - KLARA_REV=$KLARA_REV
    container_name: klara-worker
    networks:
      klaranet:
        aliases:
          - klara-worker
  klara-db:
    restart: always
    image: mariadb:10
    mem_limit: 1G
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - "G:/klara-db/datadir:/var/lib/mysql"
    container_name: klara-db
    networks:
      klaranet:
        aliases:
          - klara-db

networks:
  klaranet:
    driver: bridge